### ISSUE TITLE
在Mac OS X上安装Apache Thrift编译器

### ISSUE THREAD

**Issue by zhuangjinxin** [zhuangjinxin/thrift#1]
官方文档安装方法：
`http://thrift.apache.org/docs/install/os_x`
### OS X Setup
The following command install all the required tools and libraries to build and install the Apache Thrift compiler on a OS X based system.

### Install Boost
Download the [boost](http://www.boost.org/) library from boost.org untar compile with
```
./bootstrap.sh
sudo ./b2 threading=multi address-model=64 variant=release stage install
```

### Install libevent
Download [libevent](http://libevent.org/), untar and compile with
```
./configure --prefix=/usr/local 
make
sudo make install
```

### Building Apache Thrift
Download the latest version of [Apache Thrift](http://thrift.apache.org/download), untar and compile with
```
./configure --prefix=/usr/local/ --with-boost=/usr/local --with-libevent=/usr/local
```

官方文档的安装方法已经很简洁了

**Comment by zhuangjinxin** [comment]
在Install libevent的第三步`sudo make install`时，报错：
```
➜  libevent-2.1.8-stable sudo make install
Password:
/Applications/Xcode.app/Contents/Developer/usr/bin/make  install-am
  CC       libevent_openssl_la-bufferevent_openssl.lo
bufferevent_openssl.c:66:10: fatal error: 'openssl/bio.h' file not found
#include <openssl/bio.h>
         ^
1 error generated.
make[1]: *** [libevent_openssl_la-bufferevent_openssl.lo] Error 1
make: *** [install] Error 2
```

**Comment by zhuangjinxin** [comment]
在Building Apache Thrift时，报错！
```
...
configure: error: Bison version 2.5 or higher must be installed on the system!
```

**Comment by zhuangjinxin** [comment]
### 最后解决办法:
```
brew install thrift
```
一个安装命令搞定。前提上要安装homebrew，我之前安装过了。嗯，So就这么easy！

提示：
安装的过程比较中需要下载很多依赖软件，如果网速慢的话，耐心等待一下！

**Comment by maobaolong** [comment]
这个办法不能安装指定版本的thrift

**Comment by asdosx** [comment]
在編譯libevent時，需先在環境變數加上CFLAGS及LIBS (需先安裝openssl，再export)，接著下"./configure --prefix=/usr/local"，如此一來，產生的Makefile便會有CFLAGS與LIBS的定義，便可找到openssl的header files。
